Get rid off toJavaFormatString (closes #146)
The sun.misc.FloatingDecimal.toJavaFormatString is not available anymore in JDK11.
Since IntelliJ switched to 11 then users start getting an exception java.lang.NoClassDefFoundError: sun/misc/FloatingDecimal in runtime.

Double.toString() and Float.toString() internally calls the toJavaFormatString() so we can safely just call number.toString() even without any number.floatValue() or number.doubleValue().